### PR TITLE
Added flipX and flipY to loadSpriteFromXML()

### PR DESCRIPTION
**Pull request by THEkatinamicrowave**
why was this not already implemented? Nevermind I'm pretty sure it's because parseBool isn't a thing

### CODE REVIEW

**Comment by KadePleaseHelpMe** [comment]
NOTE: this has NOT been playtested yet

**Comment by NeeEoo** [comment]
Your repo is outdated, and removed features, please fix it before we merge

**Comment by KadePleaseHelpMe** [comment]
> Your repo is outdated, and removed features, please fix it before we merge

noted. fixing stuff rn

**Comment by KadePleaseHelpMe** [comment]
is dat gooood :>

**Comment by NeeEoo** [comment]
Id move it down to above

if (node.has.updateHitbox && node.att.updateHitbox == "true") spr.updateHitbox();

and id make it like

if (node.has.flipX && node.att.flipX == "true") spr.flipX = true;
if (node.has.flipY && node.att.flipY == "true") spr.flipY = true;

**Comment by NyxieFemboy** [comment]
Make sure this works with characters as well. Iirc characters have a different useage of flipX and most sprites in PlayState

**Comment by KadePleaseHelpMe** [comment]
> Make sure this works with characters as well. Iirc characters have a different useage of flipX from most sprites in PlayState

pretty sure that characters are added and handled differently than sprites. Sprites are **FunkinSprite**s; characters are just extents of **FlxObject**. I will double check though in case I'm dead wrong (feel free to laugh at and kill me)

**Comment by NyxieFemboy** [comment]
> > Make sure this works with characters as well. Iirc characters have a different useage of flipX from most sprites in PlayState
> 
> pretty sure that characters are added and handled differently than sprites. Sprites are **FunkinSprite** objects; characters are just extents of the **Character** class. I will double check though in case I'm dead wrong (feel free to laugh at and kill me)

You’re correct, but the nodes for character positioning in stage xmls uses the same flipX from XMLUtils

**Comment by KadePleaseHelpMe** [comment]
I'm compiling it rn; if it works it works, if it doesn't I'll fix it
I'll update as soon as I can and realize something's wrong

**Comment by KadePleaseHelpMe** [comment]
sorry it's taking so long to proofread; I had to install hscript-improved and ran update.bat which is taking forever

**Comment by KadePleaseHelpMe** [comment]
k last night my computer was being fucky wucky but now I can actually test this and see if it works

**Comment by NexIsDumb** [comment]
eh no need to check lowercase aswell, i mean look at updateHitbox
but tyy, imma prob merge it in the future

**Comment by NexIsDumb** [comment]
aight peak gameplay

image

**Pull request merged**
