### PR TITLE
Update tutorial.xml

### PR DESCRIPTION
**Pull request by megalives717**

### CODE REVIEW

**Comment by FuroYT** [comment]
That not the right repo I’m afraid you might need to pr it to the Vslice mod pack repo

**Comment by moxie-coder** [comment]
dude I swear this kid is too young to use Github

**Comment by charlesisfeline** [comment]
> what was wrong with this one?

he putt the week title from vslice

like furo said, this should be on the vslice modpack repo, not here

**Comment by PetscopF** [comment]
This is not for the main repository. PR this to the VSlice modpack repository instead.

**Comment by megalives717** [comment]
I Don't Change now!

**Pull request closed without merging**
